-- V1: Initial 4-table data model for the Lostark price tracker.
-- Flyway owns the schema (D-02); JPA runs with ddl-auto=validate and only checks agreement.
-- PostgreSQL types only (no MySQL types). All instants are TIMESTAMPTZ (stored/compared as UTC).
-- Average-price and trade-volume metrics are intentionally absent here — deferred to Task 0 / plan 01-03 (D-06).

-- Watchlist of marketable items the pipeline collects prices for.
CREATE TABLE tracked_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_item_id VARCHAR(100) NOT NULL,
    display_name     VARCHAR(200) NOT NULL,
    category         VARCHAR(100),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Time-series of collected prices. Idempotent per (item, tick): the UNIQUE constraint below
-- doubles as the (tracked_item_id, collected_at) composite index used by range queries,
-- so no separate redundant index is created.
CREATE TABLE price_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracked_item_id  BIGINT      NOT NULL REFERENCES tracked_item (id),
    collected_at     TIMESTAMPTZ NOT NULL,
    min_price        BIGINT,
    fetched_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_price_snapshot_item_time UNIQUE (tracked_item_id, collected_at)
);

-- Admin-curated game events correlated against price movements.
CREATE TABLE game_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(40)  NOT NULL,
    title       VARCHAR(300) NOT NULL,
    occurred_at TIMESTAMPTZ  NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One row per collection tick: run history (start/finish + per-item outcome counts).
CREATE TABLE collection_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL,
    finished_at     TIMESTAMPTZ,
    items_attempted INTEGER     NOT NULL DEFAULT 0,
    items_succeeded INTEGER     NOT NULL DEFAULT 0,
    items_failed    INTEGER     NOT NULL DEFAULT 0,
    status          VARCHAR(40) NOT NULL
);
