-- V5: Admin-registered coupons (coupon-admin, v1.3). New standalone domain that mirrors the
-- game_event table shape (V1) so the admin CRUD + public read stacks reuse the established pattern.
-- expires_at is DATE (D-01): coupons carry a date-only expiry — no instant/timezone column — and the
-- public endpoint judges validity on the server's KST date. The code column intentionally carries no
-- dedup index (D-04): the same coupon code may be re-registered freely (the watchlist
-- external_item_id precedent does not apply). V1–V4 stay immutable (Flyway checksums unchanged).
-- PostgreSQL types only.
CREATE TABLE coupon (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(100) NOT NULL,
    reward     VARCHAR(300) NOT NULL,
    expires_at DATE         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
