-- V6: Backfill daily-average store (timeline gap backfill, Phase 17.4). Standalone additive
-- table that holds one daily average price per (item, day, source) — the going-forward
-- YDayAvgPrice capture (D-01 source ①) and the detail-Stats material backfill (D-01 source ②)
-- both land here. price_snapshot (Core Value) is NOT touched: this is a purely additive layer
-- with its own table so collect/cache/event-impact keep zero diff (D-05, BACKFILL-04).
--
-- Idempotency (D-03): UNIQUE (tracked_item_id, stat_date, source) + ON CONFLICT DO UPDATE in the
-- repository means a server restart or the once-a-day re-run refreshes avg_price in place instead of
-- appending duplicate rows. avg_price is a traded average (e.g. 147007.4) → NUMERIC(18,4).
-- source is the DailyStatSource enum name (YDAY_AVG / DETAIL_STATS). V1–V5 stay immutable
-- (Flyway checksums unchanged). PostgreSQL types only.
CREATE TABLE item_daily_stats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracked_item_id BIGINT        NOT NULL REFERENCES tracked_item (id),
    stat_date       DATE          NOT NULL,
    avg_price       NUMERIC(18,4) NOT NULL,
    source          VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_item_daily_stats UNIQUE (tracked_item_id, stat_date, source)
);

CREATE INDEX ix_item_daily_stats_item_date ON item_daily_stats (tracked_item_id, stat_date);
