-- V9: 경매장 보석 시세 기록 (Phase 27, GEM-03). Standalone additive table — price_snapshot
-- (Core Value) is NOT touched and V1–V8 stay immutable (Flyway checksums unchanged).
--
-- Why its own table and no tracked_item FK: a gem is not a tracked_item. The auction response
-- carries no Id (Phase 24 §H5), so a gem's identity IS (series, level) — 겁화/작열 × 8/9/10.
--
-- Why this table exists at all, when Phase 26 locked "보석은 시계열 미기록": that constraint was
-- aimed at a 5분 poller (1,728 calls/day = 1.2/min off the SHARED rate-limit budget). At the 1시간
-- cadence this table is fed with, it costs 144 rows + 144 calls/day — 2% of price_snapshot's ~7,056,
-- and 0.1 calls/min against the 100/min ceiling. The rule was about frequency, not about recording.
--
-- min_buy_price NULL is MEANINGFUL and different from an absent row:
--   row + price  = we asked, 경매장 answered with a 즉시구매 listing
--   row + NULL   = we asked, there was NO 즉시구매 listing (bid-only 매물 exist — Phase 24)
--   NO row       = we could not ask (rate-limited / call failed) — never a claim about the market
-- That distinction is why no status column is needed: absence already says "we don't know".
--
-- recorded_at vs hour_slot: recorded_at is the REAL measurement instant (a 10:05 sample must not
-- claim it was taken at 10:00). hour_slot is recorded_at truncated to the hour and exists ONLY as
-- the idempotency key — UNIQUE (series, level, hour_slot) + ON CONFLICT DO NOTHING means a restart,
-- or the CI/CD redeploy storm (Phase 19 deploys on every main push), can never double-record an hour.
-- PostgreSQL types only.
CREATE TABLE gem_price_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series        VARCHAR(20) NOT NULL,
    level         SMALLINT    NOT NULL,
    min_buy_price BIGINT,
    recorded_at   TIMESTAMPTZ NOT NULL,
    hour_slot     TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_gem_price_snapshot UNIQUE (series, level, hour_slot)
);

CREATE INDEX ix_gem_price_snapshot_gem_time ON gem_price_snapshot (series, level, recorded_at);
